### ISSUE TITLE
.pbit file is incompatible with latest version of Power BI

### ISSUE THREAD

**Issue by Phillips57** [nbrown02/FlowViz#10]
Feedback Type:
Frown (Error)

Timestamp:
2020-01-14T16:15:15.7587810Z

Local Time:
2020-01-14T16:15:15.7587810+00:00

Session ID:
80249391-1f91-4747-98d5-1eef0ad02f55

Release:
January 2019

Product Version:
2.65.5313.1562 (18.12) (x86)

Error Message:
'\\********\users\******\Downloads\FlowViz - Agile Process Template.pbit' is incompatible with your current version of Microsoft Power BI Desktop. Please install the latest version and try opening the document again.

Stack Trace:
   at Microsoft.PowerBI.Client.Windows.Services.ReportFactory.ValidateVersion(String part, Version version, Version supportedVersion, Action`1 logTelemetry, ReportVersionCompatibilityFlags& versionCompatibility)
   at Microsoft.PowerBI.Client.Windows.Services.ReportFactory.DeserializeReportDocument(IStreamablePowerBIPackagePartContent streamablePowerBIPackagePartContent, IPowerBITelemetryService powerBITelemetryService, ReportVersionCompatibilityFlags& versionCompatibility)
   at Microsoft.PowerBI.Client.Windows.Services.ReportFactory.CreateReportFromPowerBIPackage(IPowerBIPackage powerBIPackage, String pbixFilePath, Byte[] securityBindings, Boolean requiresConversionToReportLayout, PowerBIPackageOpenOptions options, IPowerBITelemetryService powerBITelemetryService, IAnalysisServicesService analysisServices, PackageValidationResult& mashupValidationResult)
   at Microsoft.PowerBI.Client.Windows.Services.PowerBIPackagingService.Open(FileStream fileStream, IPowerBIWindowService windowService, Nullable`1 entryPoint, PowerBIPackageOpenOptions options, Boolean& allCredentialsSatisfied)
   at Microsoft.PowerBI.Client.Windows.Services.TemplateManager.TryImportTemplate(IPowerBIWindowService windowService, IQueryServices queryServices, IExceptionHandler exceptionHandler, TelemetryUserActionId entryPoint, Boolean& editQueries, String filePath)

Stack Trace Message:
5.2.0 is newer than the supported version (3.21.0) for report document package part

Invocation Stack Trace:
   at Microsoft.Mashup.Host.Document.ExceptionExtensions.GetCurrentInvocationStackTrace()
   at Microsoft.Mashup.Client.UI.Shared.StackTraceInfo..ctor(String exceptionStackTrace, String invocationStackTrace, String exceptionMessage)
   at Microsoft.Mashup.Client.UI.Shared.FeedbackErrorInfo..ctor(String message, Exception exception, Nullable`1 stackTraceInfo, String messageDetail)
   at Microsoft.PowerBI.Client.Windows.Services.TemplateManager.TryImportTemplate(IPowerBIWindowService windowService, IQueryServices queryServices, IExceptionHandler exceptionHandler, TelemetryUserActionId entryPoint, Boolean& editQueries, String filePath)
   at Microsoft.PowerBI.Client.Windows.Commands.ApplicationCommands.DataImportCommands.ImportTemplate(IPowerBIWindowService windowService, IExceptionHandler exceptionHandler, ImportTemplateParameters parameters)
   at Microsoft.PowerBI.Client.Windows.Commands.CommandFactory.<>c__DisplayClass42`1.<>c__DisplayClass44.<FromSyncHandlers>b__40()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.PowerBI.Client.Windows.Commands.CommandFactory.ExecuteWithExceptionHandler(Action executeMethod, IExceptionHandler exceptionHandler, String telemetryCommandName)
   at Microsoft.PowerBI.Client.Windows.Commands.CommandFactory.<>c__DisplayClass42`1.<FromSyncHandlers>b__3f(UICommandParameter`1 p)
   at Microsoft.Practices.Prism.Commands.DelegateCommand`1.<>c__DisplayClass10.<.ctor>b__c(Object o)
   at Microsoft.Practices.Prism.Commands.DelegateCommandBase.<>c__DisplayClass2.<.ctor>b__0(Object arg)
   at Microsoft.Practices.Prism.Commands.DelegateCommandBase.<Execute>d__7.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Practices.Prism.Commands.DelegateCommandBase.Execute(Object parameter)
   at Microsoft.Practices.Prism.Commands.DelegateCommand`1.<Execute>d__12.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Practices.Prism.Commands.DelegateCommand`1.Execute(T parameter)
   at Microsoft.PowerBI.Client.Windows.Commands.CompositeCommand`1.Execute(ICommand command, Object parameter)
   at Microsoft.Practices.Prism.Commands.CompositeCommand.Execute(Object parameter)
   at Microsoft.PowerBI.Client.Windows.Commands.CompositeCommand`1.Execute(T parameter)
   at Microsoft.PowerBI.Client.Windows.MainWindow.ImportTemplate(TelemetryUserActionId entryPoint, String filePath)
   at Microsoft.PowerBI.Client.Windows.MainWindow.OpenDocument(TelemetryUserActionId entryPoint, String testFilePath)
   at Microsoft.PowerBI.Client.Windows.MainWindow.OpenDocument(TelemetryUserActionId entryPoint)
   at Microsoft.PowerBI.Client.Windows.Ribbon.ApplicationRibbonCommandActionHandler.HandleCommand(UInt32 commandId)
   at Microsoft.Mashup.Client.UI.Shared.UICommands.CommandActionHandlerBase.CommandAction(UInt32 commandId)
   at Microsoft.Mashup.Client.UI.Windows.Ribbon.RibbonCommandHandler.Execute(UInt32 commandId, CommandExecutionVerb verb, PropertyKeyRef keyRef, PropVariantRef currentValue, IUISimplePropertySet commandExecutionProperties)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.RunDialog(Form form)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at Microsoft.Mashup.Client.UI.Windows.DialogWindowBase.ShowModal(IWindowHandle windowHandle)
   at Microsoft.Mashup.Client.UI.Shared.WebDialogs.WebDialog.<>n__FabricatedMethod8(IWindowHandle )
   at Microsoft.Mashup.Client.UI.Shared.WebDialogs.WebDialog.<>c__DisplayClass6.<ShowModal>b__5()
   at Microsoft.Mashup.Client.UI.Shared.WindowManager.ShowModal[T](T dialog, Func`1 showModalFunction)
   at Microsoft.Mashup.Client.UI.Shared.WebDialogs.WebDialog.ShowModal(IWindowHandle owner)
   at Microsoft.PowerBI.Client.Program.<>c__DisplayClass10.<Main>b__0()
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<>c__DisplayClass7.<HandleExceptionsWithNestedTasks>b__6()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.HandleExceptionsWithNestedTasks(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.PowerBI.Client.Program.Main(String[] args)

OS Version:
Microsoft Windows NT 10.0.17763.0 (x64 en-US)

CLR Version:
4.7 or later [Release Number = 461814]

Peak Virtual Memory:
1.36 GB

Private Memory:
360 MB

Peak Working Set:
454 MB

IE Version:
11.805.17763.0

User ID:
ed55a78c-9c0c-40ac-a226-eb38015dc99b

Workbook Package Info:
1* - en-GB, Query Groups: 0, fastCombine: Disabled, runBackgroundAnalysis: True.

Telemetry Enabled:
True

Model Default Mode:
Empty

Disabled Preview Features:
PBI_shapeMapVisualEnabled
MIntellisense
PBI_SpanishLinguisticsEnabled
PBI_PdfImport
PBI_ColumnProfiling
PBI_variationUIChange
PBI_PythonSupportEnabled
PBI_showIncrementalRefreshPolicy
PBI_showManageAggregations
PBI_FuzzyMatching
PBI_EnableWebDiagramView
PBI_improvedFilterExperience
PBI_qnaLiveConnect

Disabled DirectQuery Options:
TreatHanaAsRelationalSource

Cloud:
GlobalCloud

DPI Scale:
150%

Supported Services:
Power BI Report Server,  Power BI

Formulas:

section Section1;

**Comment by nbrown02** [comment]
@Phillips57 - is that your version of Power BI that is January 2019? If so not much I can do here, other than recommend you update to the latest version :)

**Comment by nbrown02** [comment]
Closing this as not a FlowViz issue - will update wiki to make sure it's the latest Power BI version :)
