### ISSUE TITLE
Azure DevOps Server - TagNames not found

### ISSUE THREAD

**Issue by nbrown02** [nbrown02/FlowViz#27]
Hi - couple of follow ups:
Yep, 3.0 on it's own does not work. It returns:
`{"$id":"1","innerException":null,"message":"VS403500: The v3.0 OData endpoint for Analytics is not supported. VS403503: Information on the latest recommended version is available here: https://go.microsoft.com/fwlink/?linkid=856818.","typeName":"Microsoft.VisualStudio.Services.Analytics.UnsupportedODataModelVersionException, Microsoft.VisualStudio.Services.Analytics.Server","typeKey":"UnsupportedODataModelVersionException","errorCode":0,"eventId":3000}`

v3.0-preview does return a dataset.

The workitems query has a problem after I've update the url.

```
DataSource.Error: Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: 
OData Version: 3 and 4, Error: The remote server returned an error: (400) Bad Request. (VS403483: The query specified in the URI is not valid: VS403494: No datetime offset was specified.  Please use either of these formats YYYY-MM-ddZ to specify everything since midnight or yyyy-MM-ddThh:mm-hh:mm(ISO 8601 standard representation of dates and times) to specify the offset..)
OData Version: 4, Error: The remote server returned an error: (400) Bad Request. (VS403483: The query specified in the URI is not valid: VS403494: No datetime offset was specified.  Please use either of these formats YYYY-MM-ddZ to specify everything since midnight or yyyy-MM-ddThh:mm-hh:mm(ISO 8601 standard representation of dates and times) to specify the offset..)
Details:
    DataSourceKind=OData
    DataSourcePath=http://{server}/tfs/Integration/{Project}/_odata/v3.0-preview/WorkItemSnapshot
```

If I just use the URL before the query parameters, it will return a dataset.

Last question - where would you like to continue this conversation? Please move to whatever location you feel is appropriate.
Cheers

_Originally posted by @geoandrew in https://github.com/nbrown02/FlowViz/discussions/25#discussioncomment-418729_

NOTE: not being reported by all Azure DevOps Server users

**Comment by nbrown02** [comment]
Thanks I've raised a new issue for it. I've also added a new version - could you retest?

**Comment by geoandrew** [comment]
Fails on WorkItems (Count of InProgess) with :

```
DataSource.Error: Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: 
OData Version: 3 and 4, Error: The remote server returned an error: (400) Bad Request. (VS403483: The query specified in the URI is not valid: VS403494: No datetime offset was specified.  Please use either of these formats YYYY-MM-ddZ to specify everything since midnight or yyyy-MM-ddThh:mm-hh:mm(ISO 8601 standard representation of dates and times) to specify the offset..)
OData Version: 4, Error: The remote server returned an error: (400) Bad Request. (VS403483: The query specified in the URI is not valid: VS403494: No datetime offset was specified.  Please use either of these formats YYYY-MM-ddZ to specify everything since midnight or yyyy-MM-ddThh:mm-hh:mm(ISO 8601 standard representation of dates and times) to specify the offset..)
```

Here is an object example from a listing of _odata/v3.0-preview/$metadata#WorkItemSnapshot

```
{
            "WorkItemId": 1665,
            "DateSK": 20200301,
            "DateValue": "2020-03-01T00:00:00-08:00",
            "IsLastDayOfPeriod": "Day, WeekEndingOnSunday",
            "ProjectSK": "3aa663c8-3749-4041-a52d-dba3e12c155f",
            "WorkItemRevisionSK": 20644,
            "AreaSK": "882d9cfa-eecc-46a9-bea4-e7a7f9b10609",
            "IterationSK": "f0906e67-ad4a-4153-80e8-869437ce9665",
            "AssignedToUserSK": "1edbfdee-481f-4986-aed6-5b7c10b07293",
            "ChangedByUserSK": "1edbfdee-481f-4986-aed6-5b7c10b07293",
            "CreatedByUserSK": "1edbfdee-481f-4986-aed6-5b7c10b07293",
            "ChangedDateSK": 20200114,
            "ClosedDateSK": 20200110,
            "CreatedDateSK": 20200110,
            "StateChangeDateSK": 20200110,
            "InProgressDateSK": 20200110,
            "CompletedDateSK": 20200110,
            "Revision": 3,
            "Watermark": 4259,
            "Title": "Update document library schema for collection registration",
            "WorkItemType": "Task",
            "ChangedDate": "2020-01-14T09:53:14.65-08:00",
            "CreatedDate": "2020-01-10T15:14:51.81-08:00",
            "State": "Done",
            "Reason": "Work finished",
            "ClosedDate": "2020-01-10T15:14:53.67-08:00",
            "Priority": 2,
            "ParentWorkItemId": 1601,
            "StateCategory": "Completed",
            "InProgressDate": "2020-01-10T15:14:53.67-08:00",
            "CompletedDate": "2020-01-10T15:14:53.67-08:00",
            "LeadTimeDays": 0.0000231,
            "CycleTimeDays": 0,
            "StateChangeDate": "2020-01-10T15:14:53.67-08:00",
            "Count": 1,
            "CommentCount": 0
        },
```

**Comment by nbrown02** [comment]
Nooo damn it I missed that table 👎 

Ok another version is on there now which should fix that, want to give it a go?

**Comment by geoandrew** [comment]
On Daily Blocked Count:

```
DataFormat.Error: We expected a property 'TagNames', but the OData service omitted it from the response data. This can occur for a number of reasons and does not necessarily imply that the data does not exist or is of a default value.
Details:
    Property=TagNames
```

and throws an exception:

```
Feedback Type:
Frown (Error)

Error Message:
Object reference not set to an instance of an object.

Stack Trace:
   at Microsoft.Mashup.Evaluator.ChannelMessenger.CreateChannel()
   at Microsoft.PowerBI.Client.OleDbProvider.PowerBIMashupDataSource.EvaluationSession.Dispose()
   at Microsoft.Mashup.Host.ProviderShared.PackageMashupEvaluator.<>c__DisplayClass7_0.<Evaluate>b__1(Object o)
   at Microsoft.Mashup.Evaluator.Interface.InvokeManyAction`1.CheckDone()
   at Microsoft.Mashup.OleDbProvider.DataHost.MashupEvaluator.<>c__DisplayClass4_1.<Evaluate>b__1()
   at Microsoft.Mashup.OleDbProvider.DataHost.AsyncResultIDataReaderSourceHelper.InvokeThenOnDispose(Action`1 callback, AsyncResult`1 result, Action action)
   at Microsoft.Mashup.OleDbProvider.DataHost.MashupEvaluator.<>c__DisplayClass4_0.<Evaluate>b__0(EvaluationResult2`1 result)
   at Microsoft.Mashup.Evaluator.Interface.EvaluationResultExtensions.InvokeThenOnDispose(Action`1 callback, EvaluationResult2`1 result, Action action)
   at Microsoft.Mashup.Evaluator.Interface.EvaluationResultExtensions.InvokeThenOnDispose[T](Action`1 callback, EvaluationResult2`1 result, Action action)
   at Microsoft.Mashup.Evaluator.LimitedDocumentEvaluatorFactory.Evaluation`1.Complete(EvaluationResult2`1 result)
   at Microsoft.Mashup.Evaluator.Interface.EvaluationResultExtensions.InvokeThenOnDispose(Action`1 callback, EvaluationResult2`1 result, Action action)
   at Microsoft.Mashup.Evaluator.Interface.EvaluationResultExtensions.InvokeThenOnDispose[T](Action`1 callback, EvaluationResult2`1 result, Action action)
   at Microsoft.Mashup.Evaluator.DocumentEvaluator.<>c__DisplayClass7_0`1.<BeginGetResult>b__0(EvaluationResult2`1 result)
   at Microsoft.Mashup.Evaluator.Interface.EvaluationResultExtensions.InvokeThenOnDispose(Action`1 callback, EvaluationResult2`1 result, Action action)
   at Microsoft.Mashup.Evaluator.Interface.EvaluationResultExtensions.InvokeThenOnDispose[T](Action`1 callback, EvaluationResult2`1 result, Action action)
   at Microsoft.Mashup.Evaluator.LimitedDocumentEvaluatorFactory.Evaluation`1.Complete(EvaluationResult2`1 result)
   at Microsoft.Mashup.Evaluator.RemoteDocumentEvaluator.RemoteEvaluation`1.TryComplete(EvaluationResult2`1 result)
   at Microsoft.Mashup.Evaluator.RemoteDocumentEvaluator.RemoteEvaluation`1.TryCompleteWithException(Exception exception)
   at Microsoft.Mashup.Evaluator.RemoteDocumentEvaluator.RemoteEvaluation.Evaluate(Boolean enableFirewall)
   at Microsoft.Mashup.Evaluator.EvaluatorThreadPool.EvaluatorThread(Object state)
   at Microsoft.Mashup.Evaluator.SafeThread2.<>c__DisplayClass9_0.<CreateAction>b__0(Object o)

Stack Trace Message:
Object reference not set to an instance of an object.

Invocation Stack Trace:
   at Microsoft.Mashup.Host.Document.ExceptionExtensions.GetCurrentInvocationStackTrace()
   at Microsoft.Mashup.Client.UI.Shared.StackTraceInfo..ctor(String exceptionStackTrace, String invocationStackTrace, String exceptionMessage)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.GetStackTraceInfo(Exception e)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.ReportException(IWindowHandle activeWindow, IUIHost uiHost, FeedbackPackageInfo feedbackPackageInfo, Exception e, Boolean useGDICapture)
   at Microsoft.Mashup.Client.UI.Shared.UnexpectedExceptionHandler.<>c__DisplayClass15_0.<HandleException>b__0()
   at Microsoft.Mashup.Host.Document.SynchronizationContextExtensions.<>c__DisplayClass0_1.<SendAndMarshalExceptions>b__0(Object null)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at Microsoft.Mashup.Client.UI.Windows.DialogWindowBase.ShowModal(IWindowHandle windowHandle)
   at Microsoft.Mashup.Client.UI.Shared.WindowManager.ShowModal[T](T dialog, Func`1 showModalFunction)
   at Microsoft.PowerBI.Client.Windows.FloatingDialog.KoLoadToReportDialog.TryShowDialog(Report report, IExceptionHandler exceptionHandler, IPowerBIWindowService windowService, IQueryServices queryServices, IModelingService modelingService, IUIHost uiHost, LocalizedString title, LoadToModelContext loadToModelContext, IEventAggregationService eventAggregationService)
   at Microsoft.PowerBI.Client.Windows.FloatingDialog.KoLoadToReportDialog.<>c__DisplayClass17_0.<TryShowDialogForQueriesInternal>b__0()
   at Microsoft.PowerBI.Client.Windows.Report.<>c__DisplayClass60_0`1.<SynchronizeLooselyWithQueries>b__0()
   at Microsoft.PowerBI.Client.Windows.Report.<SynchronizeLooselyWithQueriesAsync>d__61`1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerBI.Client.Windows.Report.SynchronizeLooselyWithQueriesAsync[T](Func`1 getTask)
   at Microsoft.PowerBI.Client.Windows.Report.SynchronizeLooselyWithQueries[T](Func`1 action)
   at Microsoft.PowerBI.Client.Windows.Services.TemplateManager.PromptForParametersAndCredentials(IPowerBIWindowService windowService, IQueryServices queryServices, IExceptionHandler exceptionHandler, String filePath, Report templateReport, Boolean allCredentialsSatisfied, Boolean& editQueries)
   at Microsoft.PowerBI.Client.Windows.Services.TemplateManager.TryImportTemplate(IPowerBIWindowService windowService, IQueryServices queryServices, IExceptionHandler exceptionHandler, TelemetryUserActionId entryPoint, Boolean& editQueries, String filePath)
   at Microsoft.PowerBI.Client.Windows.Commands.ApplicationCommands.DataImportCommands.ImportTemplate(IPowerBIWindowService windowService, IExceptionHandler exceptionHandler, ImportTemplateParameters parameters)
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.Practices.Prism.Commands.DelegateCommandBase.<>c__DisplayClass4_0.<.ctor>b__0(Object arg)
   at Microsoft.Practices.Prism.Commands.DelegateCommandBase.<Execute>d__10.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Practices.Prism.Commands.DelegateCommandBase.Execute(Object parameter)
   at Microsoft.Practices.Prism.Commands.DelegateCommand`1.<Execute>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Practices.Prism.Commands.DelegateCommand`1.Execute(T parameter)
   at Microsoft.PowerBI.Client.Windows.Commands.CompositeCommand`1.Execute(ICommand command, Object parameter)
   at Microsoft.Practices.Prism.Commands.CompositeCommand.Execute(Object parameter)
   at Microsoft.PowerBI.Client.Windows.Commands.CompositeCommand`1.Execute(T parameter)
   at Microsoft.PowerBI.Client.Program.<>c__DisplayClass4_7.<<Main>b__8>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerBI.Client.Program.<>c__DisplayClass4_7.<Main>b__8(MainWindow mainWindow)
   at Microsoft.PowerBI.Client.Windows.MainWindow.<<ActivateMainWindow>b__114_1>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerBI.Client.Windows.MainWindow.<ActivateMainWindow>b__114_1()
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<HandleAwaitableAsyncExceptions>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.HandleAwaitableAsyncExceptions(IExceptionHandler exceptionHandler, Func`1 asyncFunc)
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<HandleAsyncExceptions>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.HandleAsyncExceptions(IExceptionHandler exceptionHandler, Func`1 asyncFunc)
   at Microsoft.PowerBI.Client.Windows.MainWindow.<ActivateMainWindow>b__114_0()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at Microsoft.Mashup.Client.UI.Shared.WindowManager.ShowModal[T](T dialog, Func`1 showModalFunction)
   at Microsoft.PowerBI.Client.Program.<>c__DisplayClass4_0.<Main>b__1()
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<>c__DisplayClass3_0.<HandleExceptionsWithNestedTasks>b__0()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.PowerBI.Client.Program.Main(String[] args)


PowerBINonFatalError:
{"AppName":"PBIDesktop","AppVersion":"2.88.1682.0","ModuleName":"","Component":"Microsoft.Mashup.Evaluator.ChannelMessenger","Error":"Microsoft.Mashup.Host.Document.SerializedException - System.NullReferenceException","MethodDef":"CreateChannel","ErrorOffset":""}

Snapshot Trace Logs:
C:\Users\-----\AppData\Local\Microsoft\Power BI Desktop\FrownSnapShot13f9bb0b-6386-435e-81f2-3bdb4f9dc679.zip

Model Default Mode:
Empty

Model Version:
PowerBI_V1

Is Report V3 Models Enabled:
True

Enabled Preview Features:
PBI_NewWebTableInference
PBI_v3ModelsPreview

Disabled Preview Features:
PBI_shapeMapVisualEnabled
PBI_SpanishLinguisticsEnabled
PBI_JsonTableInference
PBI_ImportTextByExample
PBI_ExcelTableInference
PBI_qnaLiveConnect
PBI_eimInformationProtectionForDesktop
PBI_azureMapVisual
PBI_dataPointLassoSelect
PBI_compositeModelsOverAS
PBI_narrativeTextBox
PBI_dynamicParameters
PBI_anomalyDetection
PBI_newFieldList
PBI_cartesianMultiplesAuthoring

Disabled DirectQuery Options:
TreatHanaAsRelationalSource

Cloud:
GlobalCloud

PowerBINonFatalError_ErrorDescription:
System.NullReferenceException

PowerBIUserFeedbackServices_IsReported:
True

Formulas:


section Section1;
```

**Comment by nbrown02** [comment]
Hmm that's weird and has me flummoxed - I'll have to raise that with Microsoft as unclear what I can do differently :/

**Comment by nbrown02** [comment]
Managed to find a [similar issue](https://developercommunity.visualstudio.com/t/odata-feed-does-not-return-tagnames/787053) before - have logged it, see what Microsoft say...

**Comment by nbrown02** [comment]
Is it on every table that has TagNames or a particular table?

**Comment by geoandrew** [comment]
Looks like _OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E_ on:
- WorkItems Completed
- WorkItems In Progress
- WorkItems (Count of)
- WorkItems Blocked

Tag Names issues only on Daily Blocked Count

**Comment by nbrown02** [comment]
Thanks, I will let Microsoft know.

Does it happen on other projects? Can you also confirm you're on the latest
version of Power BI?

**Comment by nbrown02** [comment]
Hey @geoandrew - wondered if you'd had a chance to look at some of those questions? Will struggle to triage otherwise :(

**Comment by geoandrew** [comment]
Hi - sorry for the delay. Got caught up in some other work.

- Power BI Desktop Version 2.90.782.0 64-bit (February, 2021) - just updated

Running this query in the browser returns a dataset
`
http://tfs.interiorhealth.ca:8080/tfs/Integration/Clinical%20Data%20Exchange/_odata/v3.0-preview/WorkItems?%20$filter=WorkItemType%20ne%20%27Issue%27%20and%20WorkItemType%20ne%20%27Task%27%20and%20WorkItemType%20ne%20%27Test%20Case%27%20and%20WorkItemType%20ne%20%27Test%20Plan%27%20and%20WorkItemType%20ne%20%27Shared%20Parameter%27%20and%20WorkItemType%20ne%20%27Shared%20Steps%27%20and%20WorkItemType%20ne%20%27Test%20Suite%27%20and%20WorkItemType%20ne%20%27Impediment%27%20and%20State%20ne%20%27Removed%27%20&$select=AreaSK,CompletedDate,CompletedDateSK,CycleTimeDays,IterationSK,LeadTimeDays,ParentWorkItemID,State,StateCategory,TagNames,Title,WorkItemID,WorkItemType
`
it includes:
```
"@odata.context": "http://ourhostname:8080/tfs/Integration/Clinical%20Data%20Exchange/_odata/v3.0-preview/$metadata#WorkItems(AreaSK,CompletedDate,CompletedDateSK,CycleTimeDays,IterationSK,LeadTimeDays,ParentWorkItemId,State,StateCategory,TagNames,Title,WorkItemId,WorkItemType)",
    "vsts.warnings@odata.type": "#Collection(String)",
    "@vsts.warnings": [
        "VS403509: The specified query exceeds the recommended size of 10 columns. Details on recommended query patterns are available here: https://go.microsoft.com/fwlink/?linkid=861060."
    ],
```
Included fields are :
```
"value": [
        {
            "AreaSK": "25fa3a47-41b2-4a50-bf5a-8b3b5395f499",
            "IterationSK": "b73bc632-3efe-4062-ba14-7718607d1501",
            "State": "New",
            "StateCategory": "Proposed",
            "Title": "FHIR Bundle Processing Enhancements",
            "WorkItemId": 1975,
            "WorkItemType": "Product Backlog Item"
        },
        {
```

Cannot test in other projects at this stage.
hth

cheers

**Comment by nbrown02** [comment]
Thanks - that query is the same as in Power BI so something isn't right :/ 

What version of Azure DevOps Server are you on?

**Comment by geoandrew** [comment]
Can confirm server 2019

**Comment by nbrown02** [comment]
Perfect thanks - back to Microsoft I go!

**Comment by nbrown02** [comment]
@geoandrew Microsoft replied with:

```
According to your description, if the data query:
https://tfs.interiorhealth.ca:8080/tfs/Integration/Clinical Data Exchange/_odata/v3.0-preview/WorkItemSnapshot? $apply=filter(%20StateCategory%20ne%20%27Proposed%27%20and%20State%20ne%20%27Removed%27%20and%20StateCategory%20ne%20%27Completed%27%20and%20WorkItemType%20ne%20%27Task%27%20and%20WorkItemType%20ne%20%27Epic%27%20and%20WorkItemType%20ne%20%27Feature%27%20and DateValue ge 2020-01-01Z)%20/groupby(%20(DateValue,DateSK,AreaSK,TagNames),%20aggregate($count%20as%20Count)%20)

works fine in the browser, it should be related to the Power BI.

You could try to update the Power BI and try to check with other projects.
```

**Comment by nbrown02** [comment]
After testing with some other Azure DevOps Server users, we're unable to reproduce this issue.

Closing for now, will reopen if it happens elsewhere.

**Comment by nbrown02** [comment]
@geoandrew - reopening as I may have found a way around this, just working through at the minute

**Comment by nbrown02** [comment]
Fixed in latest version 💯
